sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: 
    username: 
    password: 
  alioss:
    access-key-id: 
    access-key-secret: 
    bucket-name: 
    endpoint: 
